name: OmniWorldMC
main: com.omniworldmc.plugin.OmniWorldMC
version: 1.8-15.16.4-R0.3-B
commands:
   om:
      description: The Main Command
      usage: /<command>
   rage:
      description: The Rage Command
      usage: /<command>