name: OmniWorldMC
main: com.omniworldmc.plugin.OmniWorldMC
version: 1.0.0-RELEASE
commands:
   om:
      description: The Main Command
      usage: /<command>
   rage:
      description: The Rage Command
      usage: /<command>