name: OmniWorldMC
main: com.omniworldmc.plugin.OmniWorldMC
version: 1.1.1
author: OmniWorldMC Development Team
authors: [Chaka, MrL314, creatorsuperman]
commands:
   om:
      description: The main command.
      usage: /<command>